//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int Id_Material { get; set; }
        public string Name_Material { get; set; }
        public Nullable<int> Id_TypeMaterial { get; set; }
        public Nullable<int> Count_OnPackage { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Count_InWarehouse { get; set; }
        public Nullable<int> MinRemain { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual TypeMaterial TypeMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
