//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int Articul_Product { get; set; }
        public string Name_Product { get; set; }
        public Nullable<double> MinPrice { get; set; }
        public string Image { get; set; }
        public Nullable<int> Id_TypeProduct { get; set; }
        public Nullable<int> MinCount_Workers { get; set; }
        public Nullable<int> Worshop_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
        public virtual Type_Product Type_Product { get; set; }
    }
}
