//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public int Id_ProductMaterial { get; set; }
        public Nullable<int> Articul_Product { get; set; }
        public Nullable<int> Id_Material { get; set; }
        public Nullable<int> Count_Material { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
